NWMvcApp/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NWMvcApp.Models;

namespace NWMvcApp.Controllers
{
    public class EmployeeController : Controller
    {
        //
        // GET: /Employee/

        public ActionResult Index()
        {
            var entities = new NWEntities();
            var emps = entities.Employees;
            
            return View(new EmployeeModel
            {
                EmployeeList = emps.ToList()
            });
        }

        //
        // GET: /Employee/Details/5

        public ActionResult Details(int id)
        {
            //return View();
            return null;
        }

        //
        // GET: /Employee/Create

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Employee/Create

        [HttpPost]
        public ActionResult Create(EmployeeModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                var entities = new NWEntities();
                entities.Employees.Add(
                    new Employee
                    {
                        LastName = model.LastName,
                        FirstName = model.FirstName,
                        Title = model.Title,
                        HireDate = model.HireDate,
                        BirthDate = model.BirthDate,
                        Address = model.Address,
                        City = model.City,
                        Region = model.Region,
                        PostalCode = model.Postal
                    });

                entities.SaveChanges();


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Employee/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Employee/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                //return View();
                return null;
            }
        }

        //
        // GET: /Employee/Delete/5

        public ActionResult Delete(int id)
        {
            //return View();
            return null;
        }

        //
        // POST: /Employee/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                //return View();
                return null;
            }
        }
    }
}

NWMvcApp/Views/Employee/Create.cshtml
@model NWMvcApp.Models.EmployeeModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Employee</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <p>
        Last name: @Html.TextBoxFor(m => Model.LastName)
    </p>

    <p>
        First name: @Html.TextBoxFor(m => Model.FirstName)
    </p>

    <p>
        Title: @Html.TextBoxFor(m => m.Title)
    </p>

    <p>
        Birth date: @Html.TextBoxFor(m=>Model.BirthDate)
    </p>
    
    <p>
        Address: @Html.TextBoxFor(m=>Model.Address)
    </p>

    <p>
        City: @Html.TextBoxFor(m=>Model.City)
    </p>

    <p>
        Region: @Html.TextBoxFor(m=>m.Region)
    </p>

    <p>
        Postal: @Html.TextBoxFor(m=>m.Postal)
    </p>

    <p>
        Hire date: @Html.TextBoxFor(m=>Model.HireDate)
    </p>
    
    <p>
        <input type="submit" value="submit"/> &nbsp;
        @Html.ActionLink("Back", "Index", "Employee")
    </p>

    
}

NWMvcApp/Views/Employee/Index.cshtml
@model NWMvcApp.Models.EmployeeModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Employees</h2>

@Html.ActionLink("Add New", "Create", "Employee")


<table class="table table-striped">
    <tr>
        <td>Name</td>
        <td>Title</td>
        <td>Birth date</td>
        <td>Hire date</td>
        <td>Address</td>
        <td>City</td>
        <td>Region</td>
        <td>Postal code</td>
    </tr>

    @foreach (var e in Model.EmployeeList)
    {
        <tr>
            <td>@e.TitleOfCourtesy @e.FirstName @e.LastName</td>
            <td>@e.Title </td>
            <td>@e.BirthDate.Value.ToShortDateString()</td>
            <td>@e.HireDate.Value.ToShortDateString()</td>
            <td>@e.Address</td>
            <td>@e.City</td>
            <td>@e.City</td>
            <td>@e.PostalCode</td>
        </tr>
    }

</table>