NWMvcApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NWMvcApp.Models;

namespace NWMvcApp.Controllers
{
    public class CustomerController : Controller
    {
        //
        // GET: /Customer/

        public ActionResult Index()
        {
            var entities = new NWEntities();
            var customers = entities.Customers;

            return View(
                new CustomerModel
                {
                    CustomerList = customers.ToList()
                });
        }

        //
        // GET: /Customer/Details/5

        public ActionResult Details(int id)
        {
            //return View();
            return null;
        }

        //
        // GET: /Customer/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Customer/Create

        [HttpPost]
        public ActionResult Create(CustomerModel model)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View();
                }

                var entities = new NWEntities();
                entities.Customers.Add(new Customer
                {
                    CustomerID = model.CustomerId,
                    CompanyName = model.CompanyName,
                    ContactName = model.ContactName
                });

                entities.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        //
        // GET: /Customer/Edit/5

        public ActionResult Edit(int id)
        {
            //return View();
            return null;
        }

        //
        // POST: /Customer/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                //return View();
                return null;
            }
        }

        //
        // GET: /Customer/Delete/5

        public ActionResult Delete(int id)
        {
            //return View();
            return null;
        }

        //
        // POST: /Customer/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                //return View();
                return null;
            }
        }
    }
}

NWMvcApp/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using NWMvcApp.Models;

namespace NWMvcApp.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/

        public ActionResult Index()
        {

            var entities = new NWEntities();
            var products = entities.Products;

            return View(new ProductModel
            {
                ProductList = products.ToList()
            });
        }

        //
        // GET: /Product/Details/5

        public ActionResult Details(int id)
        {
            var entities = new NWEntities();
            var product = entities.Products
                .Include("Supplier")
                .Include("Category")
                .SingleOrDefault(x => x.ProductID == id);
            
            
            return View(new ProductModel
            {
                ProductName = product.ProductName,
                SupplierID = product.SupplierID,
                Supplier = product.Supplier,
                Category = product.Category,
                QuantityPerUnit = product.QuantityPerUnit,
                UnitPrice = product.UnitPrice,
                UnitsInStock = product.UnitsInStock,
                UnitsOnOrder = product.UnitsOnOrder,
                ReorderLevel = product.ReorderLevel,
                Discontinued = product.Discontinued
            });
        }

        //
        // GET: /Product/Create

        [HttpGet]
        public ActionResult Create()
        {
            if (Session["SuppliersList"] == null || Session["CategoriesList"]==null)
            {
                GetSuppliersAndCats();
            }

            return View(new ProductModel
            {
                SupplierSelectList = GetSupplierSelectList((List<Supplier>)Session["SuppliersList"]),
                CategorySelectList = GetCategorySelectList((List<Category>)Session["CategoriesList"])
            });
        }

        //
        // POST: /Product/Create
        [HttpPost]
        public ActionResult Create(ProductModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(new ProductModel
                    {
                        SupplierSelectList = GetSupplierSelectList((List<Supplier>)Session["SuppliersList"]),
                        CategorySelectList = GetCategorySelectList((List<Category>)Session["CategoriesList"])
                    });
                }


                
                var entities = new NWEntities();
                entities.Products.Add(new Product
                {
                    ProductName = model.ProductName,
                    SupplierID = model.SelectedSupplierItem,
                    CategoryID = model.SelectedCategoryItem,
                    QuantityPerUnit = model.QuantityPerUnit,
                    UnitPrice = model.UnitPrice,
                    UnitsInStock = model.UnitsInStock,
                    UnitsOnOrder = model.UnitsOnOrder,
                    ReorderLevel = model.ReorderLevel,
                    Discontinued = model.Discontinued
                });
                entities.SaveChanges();


                return View(new ProductModel
                {
                    SupplierSelectList = GetSupplierSelectList((List<Supplier>)Session["SuppliersList"]),
                    CategorySelectList = GetCategorySelectList((List<Category>)Session["CategoriesList"])
                });
            }
            catch
            {
                return View(new ProductModel
                {
                    SupplierSelectList = GetSupplierSelectList((List<Supplier>)Session["SuppliersList"]),
                    CategorySelectList = GetCategorySelectList((List<Category>)Session["CategoriesList"])
                });
            }
        }

        //
        // GET: /Product/Edit/5

        public ActionResult Edit(int id)
        {
            //return View();
            return null;
        }

        //
        // POST: /Product/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                //return View();
                return null;
            }
        }

        //
        // GET: /Product/Delete/5

        public ActionResult Delete(int id)
        {
            //return View();
            return null;
        }

        //
        // POST: /Product/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                //return View();
                return null;
            }
        }

        private static SelectList GetSupplierSelectList(IEnumerable<Supplier> suppliers)
        {
            var items = suppliers.Select(o => new { Value = o.SupplierID, Text = o.ContactName });
            return new SelectList(items, "Value", "Text");
        }

        private static SelectList GetCategorySelectList(IEnumerable<Category> categories)
        {
            var items = categories.Select(o => new { Value = o.CategoryID, Text = o.CategoryName });
            return new SelectList(items, "Value", "Text");
        }

        private void GetSuppliersAndCats()
        {
            var entities = new NWEntities();
            var suppliers = entities.Suppliers.ToList<Supplier>();
            var categories = entities.Categories.ToList<Category>();

            Session["SuppliersList"] = suppliers;
            Session["CategoriesList"] = categories;        
        }

    }

}

NWMvcApp/Views/Product/Create.cshtml
@model NWMvcApp.Models.ProductModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New</h2>


@using (Html.BeginForm())
{
    <h2>Create Product</h2>

    @Html.ValidationSummary()
    <p>
        Product Name: @Html.TextBoxFor(m => Model.ProductName)
    </p>

    <p>
        Supplier: 
        @Html.DropDownListFor(x => x.SelectedSupplierItem, Model.SupplierSelectList, "", 
            new { id = "SupplierSelectList", name = "SupplierSelectList", style = "width:300px;", @class = "form-control" })      
    </p>

    <p>
        Category:
        @Html.DropDownListFor(x => x.SelectedCategoryItem, Model.CategorySelectList, "",
              new { id = "CategorySelectList", name = "CategorySelectList", style = "width:300px;", @class = "form-control" })
        
    </p>

    <p>
        Qty per unit: @Html.TextBoxFor(m => Model.QuantityPerUnit)
    </p>

    <p>
        Unit price: @Html.TextBoxFor(m => Model.UnitPrice)
    </p>

    <p>
        Units in stock: @Html.TextBoxFor(m => Model.UnitsInStock)
    </p>

    <p>
        Units on order: @Html.TextBoxFor(m => Model.UnitsOnOrder)
    </p>

    <p>
        Reorder level: @Html.TextBoxFor(m => Model.ReorderLevel)
    </p>

    <p>
        Discontinued: @Html.CheckBoxFor(m => Model.Discontinued)
    </p>
    
    <p>
        <input value="submit" type="submit" name="submit" /> &nbsp;
        @Html.ActionLink("Back", "Index", "Customer")
    </p>
}

NWMvcApp/Views/Product/Details.cshtml
@model NWMvcApp.Models.ProductModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Product Details</h2>

<table width="45%" cellpadding="3" cellspacing="3">
    <tr>
        <td>Name:</td>
        <td>@Model.ProductName</td>
    </tr>
    <tr>
        <td>Supplier:</td>
        <td>@Model.Supplier.CompanyName</td>
    </tr>
    <tr>
        <td>Category:</td>
        <td>@Model.Category.CategoryName</td>
    </tr>
    <tr>
        <td>Qty per unit:</td>
        <td>@Model.QuantityPerUnit</td>
    </tr>
    <tr>
        <td>Unit price:</td>
        <td>@Model.UnitPrice</td>
    </tr>
    <tr>
        <td>Units in stock:</td>
        <td>@Model.UnitsInStock</td>
    </tr>
    <tr>
        <td>Units on order:</td>
        <td>@Model.UnitsOnOrder</td>
    </tr>
    <tr>
        <td>Reorder level:</td>
        <td>@Model.ReorderLevel</td>
    </tr>
    <tr>
        <td>Discontinued:</td>
        <td>@Model.Discontinued</td>
    </tr>
</table>

NWMvcApp/Views/Product/Index.cshtml
@using NWMvcApp.Models
@model NWMvcApp.Models.ProductModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Products</h2>

<form>
    
    @Html.ActionLink("Add New", "Create", "Product")

    <table class="table table-striped">
        <tr>
            <td>
                Product Name
            </td>
            <td>
                Supplier
            </td>
        </tr>
        @foreach (var p in Model.ProductList)
        {
            <tr>
                <td>
                    @Html.ActionLink(p.ProductName, "Details", new { @id = p.ProductID})
                </td>
                <td>
                    @p.Supplier.CompanyName
                </td>
            </tr>
        }
    </table>



</form>